
[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "Always"

[env]
TERM = "alacritty"

[font]
size = 12.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.normal]
family = "Fira Code"
style = "Retina"

[selection]
save_to_clipboard = true

[general]
import = ["/home/bgarber/.alacritty-themes/onehalf.toml"]
