#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.
#
# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# Turn off annoying system bell
xset b off &

# Turn on true transparency
xcompmgr -c &

# Set the last wallpaper
fbsetbg -l

# Turn up the screensaver
xscreensaver -no-splash &

# Gnome keyring
gnome-keyring-daemon --start --components=gpg,ssh,secrets,pkcs11 &

# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/bgarber/.fluxbox/log"
